kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:alpine
    commands:
      - npm install
      - npm run build
      - echo $DRONE_COMMIT > version.txt

  - name: unit tests
    image: node:alpine
    commands:
      - npm run test
trigger:
  branch:
    - master
