kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:alpine
    commands:
      - npm install
      - npm run build

  - name: unit tests
    image: node:alpine
    commands:
      - npm run test
trigger:
  branch:
    - master
